Demo site
publiclab/spectral-workbench.js pull request #175
Opened 2020-09-05 00:53 UTC by TonyIversonLin

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- see README.md for how to run them
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request are descriptively named
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

2020-09-17 16:37 UTC, jywarren commented on examples/new-capture/index_copy.html
> +<!DOCTYPE html>
Just wondering how this is distinct from `index.html`? Thank you!

2020-09-17 16:43 UTC, jywarren requested changes
This looks fantastic! A couple small notes and requests:

1. I noticed a `.DS_Store` file was added, probably inadvertently - can you just remove that? Thanks!
2. The copy of the `new-capture` JS files seems like it could diverge development of those files, which may be changing quickly. Was it intentional to make 2 copies of each, and are they exact copies? 
3. The `new-capture` index.html is still pointed at `dist/capture.dist.js`, and that file is compiled from the `examples/capture/*.js` files, not the new `new-capture` copies, so i believe the new copies are not being used in this demo, is that correct? Below is the Gruntfile code which compiles the files:

https://github.com/publiclab/spectral-workbench.js/blob/5b176c52fe9ecf0e4fd533c2390c40b43c783260/Gruntfile.js#L49-L57

Thanks, just need a little clarity on these but overall this is looking really fantastic. I love your final report as well, would you be able to share that in this PR somehow for other contributors to read? 

Great work, we're almost there!! Many thanks!

2020-09-17 16:43 UTC, jywarren commented on examples/new-capture/index.html
> +  <script src="../../dist/capture.dist.js" type="text/javascript"></script>
This is pointed at the compiled file, see review note about Grunt compilation! Thanks!

2020-09-17 16:46 UTC, jywarren commented
I'm also seeing an odd error in our Travis build:

```
27.02s$ npm ci 
> cypress@5.1.0 postinstall /home/travis/build/publiclab/spectral-workbench.js/node_modules/cypress
> node index.js --exec install
> cypress@5.1.0 postinstall /home/travis/build/publiclab/spectral-workbench.js/node_modules/cypress
> node index.js --exec install
/home/travis/build/publiclab/spectral-workbench.js/node_modules/cypress/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
```

https://travis-ci.com/github/publiclab/spectral-workbench.js/builds/182860297#L399-L407

This seems related to the `npm ci` command and/or the `postinstall` stage of cypress. Does this happen to you on local?

2020-09-17 16:50 UTC, jywarren commented
And, just confirming that the new capture demo works! Presumably using the compiled (and previous) capture code:

![Screen Shot 2020-09-17 at 12 49 06 PM](https://user-images.githubusercontent.com/24359/93502146-5d505880-f8e4-11ea-8264-a788ecd5d435.png)
![Screen Shot 2020-09-17 at 12 49 14 PM](https://user-images.githubusercontent.com/24359/93502150-5de8ef00-f8e4-11ea-906d-0e832989f9df.png)

A couple icons aren't showing, but it's a minor issue!

2020-09-17 16:53 UTC, jywarren commented
Ah, i am getting an error and no graph on the final "save graph" step:

![Screen Shot 2020-09-17 at 12 51 13 PM](https://user-images.githubusercontent.com/24359/93502283-8375f880-f8e4-11ea-9e3c-8c423f9fc850.png)

It looks like `d3` is not getting loaded? 

```
Uncaught ReferenceError: d3 is not defined
    at Class.init (spectral-workbench.js:5178)
    at new Class (spectral-workbench.js:62)
```

`[2020-09-17T16:48:25.081Z]  "GET /bower_components/d3/d3.js" Error (404): "Not found"`

Perhaps it has to be included via NPM instead of bower -- the correct route should be `/node_modules/d3/d3.js`, no?

2020-09-17 16:55 UTC, jywarren commented on bower.json
> +    "jquery.steps": "^1.1.0"
Here I think we should move this to the `package.json` file, as we are trying to stop using Bower. I believe all existing dependencies have already been moved, too!

2020-09-17 16:57 UTC, jywarren commented on examples/new-capture/index.html
> +  <script src="../../bower_components/jquery.steps/build/jquery.steps.min.js"></script>
Yes - here, and below, all instances of `bower_components` should be changed to `node_modules` and all dependencies but `jquery.steps` have been transferred there already. That should resolve the last error on the final "plotting" page of the new demo!

2020-09-17 16:58 UTC, jywarren commented on bower.json
> +    "jquery.steps": "^1.1.0"
https://github.com/publiclab/spectral-workbench.js/blob/5b176c52fe9ecf0e4fd533c2390c40b43c783260/package.json#L27

2020-09-17 17:20 UTC, TonyIversonLin commented
If you open the original index.html file, it has a hyper link to the new
demo site. Also please do another npm install and bower install before
running the new demo page. Thanks.

On Thu, Sep 17, 2020, 12:37 PM Jeffrey Warren <notifications@github.com>
wrote:

> *@jywarren* commented on this pull request.
> ------------------------------
>
> In examples/new-capture/index_copy.html
> <https://github.com/publiclab/spectral-workbench.js/pull/175#discussion_r490403300>
> :
>
> > @@ -0,0 +1,363 @@
> +<!DOCTYPE html>
>
> Just wondering how this is distinct from index.html? Thank you!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/publiclab/spectral-workbench.js/pull/175#pullrequestreview-490789790>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEX5LH3NKMVLSEKY6JCM2N3SGI3MNANCNFSM4QZYQAIQ>
> .
>

2020-09-17 17:23 UTC, TonyIversonLin commented
Awesome

On Thu, Sep 17, 2020, 12:57 PM Jeffrey Warren <notifications@github.com>
wrote:

> *@jywarren* commented on this pull request.
> ------------------------------
>
> In examples/new-capture/index.html
> <https://github.com/publiclab/spectral-workbench.js/pull/175#discussion_r490416187>
> :
>
> > +  <link rel="apple-touch-fa-precomposed" href="//spectralworkbench.org/images/spectral-workbench-256.png">
> +  <link rel="apple-touch-fa-precomposed apple-touch-icon" href="//spectralworkbench.org/images/spectral-workbench-256.png">
> +  <link rel="shortcut icon" href="//spectralworkbench.org/images/spectral-workbench-256.png" />
> +
> +  <link rel="stylesheet" href="../../node_modules/font-awesome/css/font-awesome.min.css"/>
> +  <link rel="stylesheet" href="../../node_modules/bootstrap/dist/css/bootstrap.min.css"/>
> +  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bs-stepper/dist/css/bs-stepper.min.css">
> +
> +  <script src="https://kit.fontawesome.com/a076d05399.js"></script>
> +  <script src="../../node_modules/getusermedia-js/dist/getUserMedia.min.js"></script>
> +  <script src="../../node_modules/jquery/dist/jquery.min.js"></script>
> +  <script src="../../node_modules/flot/jquery.flot.js"></script>
> +  <script src="../../node_modules/flot/jquery.flot.crosshair.js"></script>
> +  <script src="../../node_modules/flot/jquery.flot.threshold.js"></script>
> +  <script src="../../node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
> +  <script src="../../bower_components/jquery.steps/build/jquery.steps.min.js"></script>
>
> Yes - here, and below, all instances of bower_components should be
> changed to node_modules and all dependencies but jquery.steps have been
> transferred there already. That should resolve the last error on the final
> "plotting" page of the new demo!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/publiclab/spectral-workbench.js/pull/175#pullrequestreview-490805749>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEX5LH2T2BV5EOF3NAIPDM3SGI5XHANCNFSM4QZYQAIQ>
> .
>

2020-09-17 17:31 UTC, TonyIversonLin commented
Hi Jeff,

that is correct. The new demo did not use the new capture module which
allow user to adjust resolution.

On Thu, Sep 17, 2020, 12:43 PM Jeffrey Warren <notifications@github.com>
wrote:

> *@jywarren* requested changes on this pull request.
>
> This looks fantastic! A couple small notes and requests:
>
>    1. I noticed a .DS_Store file was added, probably inadvertently - can
>    you just remove that? Thanks!
>    2. The copy of the new-capture JS files seems like it could diverge
>    development of those files, which may be changing quickly. Was it
>    intentional to make 2 copies of each, and are they exact copies?
>    3. The new-capture index.html is still pointed at dist/capture.dist.js,
>    and that file is compiled from the examples/capture/*.js files, not
>    the new new-capture copies, so i believe the new copies are not being
>    used in this demo, is that correct? Below is the Gruntfile code which
>    compiles the files:
>
>
> https://github.com/publiclab/spectral-workbench.js/blob/5b176c52fe9ecf0e4fd533c2390c40b43c783260/Gruntfile.js#L49-L57
>
> Thanks, just need a little clarity on these but overall this is looking
> really fantastic. I love your final report as well, would you be able to
> share that in this PR somehow for other contributors to read?
>
> Great work, we're almost there!! Many thanks!
> ------------------------------
>
> In examples/new-capture/index.html
> <https://github.com/publiclab/spectral-workbench.js/pull/175#discussion_r490405808>
> :
>
> > +  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bs-stepper/dist/css/bs-stepper.min.css">
> +
> +  <script src="https://kit.fontawesome.com/a076d05399.js"></script>
> +  <script src="../../node_modules/getusermedia-js/dist/getUserMedia.min.js"></script>
> +  <script src="../../node_modules/jquery/dist/jquery.min.js"></script>
> +  <script src="../../node_modules/flot/jquery.flot.js"></script>
> +  <script src="../../node_modules/flot/jquery.flot.crosshair.js"></script>
> +  <script src="../../node_modules/flot/jquery.flot.threshold.js"></script>
> +  <script src="../../node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
> +  <script src="../../bower_components/jquery.steps/build/jquery.steps.min.js"></script>
> +  <script src="graph.js" type="text/javascript"></script>
> +  <script src="https://cdn.jsdelivr.net/npm/bs-stepper/dist/js/bs-stepper.min.js"></script>
> +
> +
> +  <script src="capture.js" type="text/javascript"></script>
> +  <script src="../../dist/capture.dist.js" type="text/javascript"></script>
>
> This is pointed at the compiled file, see review note about Grunt
> compilation! Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/publiclab/spectral-workbench.js/pull/175#pullrequestreview-490792860>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEX5LHYISH2KQSM66KJ3BKTSGI4EJANCNFSM4QZYQAIQ>
> .
>

2020-09-18 16:21 UTC, jywarren commented
Hi @TonyIversonLin - so, can we delete the extra copies of the JS files in the `new-capture` folder, since it's all running from the `/dist/____` versions anyways? Thank you!

2020-09-18 20:09 UTC, TonyIversonLin commented
Yes I think we can delete those.

On Fri, Sep 18, 2020, 12:22 PM Jeffrey Warren <notifications@github.com>
wrote:

> Hi @TonyIversonLin <https://github.com/TonyIversonLin> - so, can we
> delete the extra copies of the JS files in the new-capture folder, since
> it's all running from the /dist/____ versions anyways? Thank you!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/publiclab/spectral-workbench.js/pull/175#issuecomment-694961099>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEX5LH57HCA4Z6PVV5ZZK33SGOCMBANCNFSM4QZYQAIQ>
> .
>

2020-09-22 21:14 UTC, jywarren commented
I believe this is ready to go except for the Cypress-related test error!

Noting that we do need a way to download the spectrum output in a file, either CSV or JSON. We can do this in follow-up.

2020-09-22 22:25 UTC, jywarren commented
Ohoho -- `The command "bower install" failed and exited with 1 during .`

2020-09-22 22:29 UTC, jywarren commented
Hmm, back to:

```
> cypress@5.1.0 postinstall /home/travis/build/publiclab/spectral-workbench.js/node_modules/cypress
> node index.js --exec install
/home/travis/build/publiclab/spectral-workbench.js/node_modules/cypress/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^
```

We should search for that error to see what's up with Cypress!

2020-09-22 23:55 UTC, TonyIversonLin commented
Definitely.  We don't really need the cypress test.

On Tue, Sep 22, 2020, 5:14 PM Jeffrey Warren <notifications@github.com>
wrote:

> I believe this is ready to go except for the Cypress-related test error!
>
> Noting that we do need a way to download the spectrum output in a file,
> either CSV or JSON. We can do this in follow-up.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/publiclab/spectral-workbench.js/pull/175#issuecomment-696985708>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEX5LHYRGBZWJRASHJTUVW3SHEHTNANCNFSM4QZYQAIQ>
> .
>

2020-09-23 03:52 UTC, jywarren commented
Maybe https://on.cypress.io/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI 

Or https://github.com/cypress-io/cypress/issues/1297 ?

2020-09-23 22:51 UTC, jywarren commented on .travis.yml
>    - '8'
https://docs.cypress.io/guides/guides/continuous-integration.html#Travis

2020-09-23 22:54 UTC, jywarren commented on .travis.yml
>  language: node_js
And another example here: https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.travis.yml

2020-09-24 00:11 UTC, jywarren commented
Almost there!!!!

```
http://127.0.0.1:8080/examples/new-capture/
We attempted to make an http request to this URL but the request failed without a response.
We received this error at the network level:
  > Error: connect ECONNREFUSED 127.0.0.1:8080
```

OK, so we need to point that at the correct page!

2020-09-24 00:12 UTC, jywarren commented on cypress/integration/spectral-workbench-demo.spec.js
> +    cy.visit('http://127.0.0.1:8080/examples/new-capture/')
Let's change this!

2020-09-24 00:43 UTC, jywarren commented
Yay! The test is running!

```
  1) Actions
       "before each" hook for "It reach the default landing page":
     ReferenceError: The following error originated from your application code, not from Cypress.
  > AdapterJS is not defined
When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
```

2020-09-24 00:49 UTC, jywarren commented
Something's wrong with d3...

```
   - can export SVG...X can export SVG
     TypeError: undefined is not an object (evaluating 'd3.select('svg').data()[0][index].id') in file:///home/travis/build/publiclab/spectral-workbench.js/dist/spectral-workbench.js (line 5374) (1)
```

2020-09-24 00:51 UTC, jywarren commented on Gruntfile.js
> +                'node_modules/d3/d3.js',
Could something be wrong with this line, for jasmine?

2020-09-24 00:55 UTC, jywarren commented
Oh hmm, a bunch of Jasmine is broken:

```

     TypeError: undefined is not an object (evaluating 'd3.select('svg').data()[0][index].id') in file:///home/travis/build/publiclab/spectral-workbench.js/dist/spectral-workbench.js (line 5374) (1)
   - can copy calibrations with copyCalibration()...X can copy calibrations with copyCalibration()
     TypeError: undefined is not an object (evaluating 'graph.datum') in file:///home/travis/build/publiclab/spectral-workbench.js/spec/javascripts/api_spec.js (line 128) (1)
   - generates copyCalibration callback...X generates copyCalibration callback
     Expected spy success to have been called. (1)
   - can transform graph data...X can transform graph data
     TypeError: undefined is not an object (evaluating 'graph.datum') in file:///home/travis/build/publiclab/spectral-workbench.js/spec/javascripts/api_spec.js (line 156) (1)
   - can limit graphed data to wavelength range...X can limit graphed data to wavelength range
     TypeError: undefined is not an object (evaluating 'graph.datum') in file:///home/travis/build/publiclab/spectral-workbench.js/spec/javascripts/api_spec.js (line 168) (1)
   - can blend graphed spectrum data with that of another spectrum...X can blend graphed spectrum data with that of another spectrum
```

2020-09-29 15:06 UTC, jywarren commented on Gruntfile.js
> +                'node_modules/d3/d3.js',
Hmm. `  <script src="../../node_modules/d3/d3.js" type="text/javascript"></script>` indicates not...

2020-09-29 16:13 UTC, jywarren commented
OK, this is odd. But regarding:

>      TypeError: undefined is not an object (evaluating 'graph.datum') in file:///home/travis/build/publiclab/spectral-workbench.js/spec/javascripts/api_spec.js (line 128) (1)

That `graph` object is defined in the previous test: 

https://github.com/publiclab/spectral-workbench.js/blob/8d0526d9c7efbb80b3356582b40ce3546b6c785a/spec/javascripts/api_spec.js#L103

Is there an order of execution issue happening? No, i think perhaps the SVG test failure is causing the `graph` object not to be initialized. Let's focus on the SVG test.

2020-09-29 16:50 UTC, jywarren commented
OK, reproduced it by going to the graph example at /examples/index.html, copying `/spec/javascript/fixtures/spectrum-9.json` to `/spectrums/9.json` (so the aync fetch of the data works), then running:

```js
graph2 = new SpectralWorkbench.Graph({
      spectrum_id: 9,
      calibrated: true,
      onImageComplete: function() { done(); }
    });
```

Here's the full trace:

```
Uncaught TypeError: Cannot read property 'id' of undefined
    at SVGGElement.<anonymous> (spectral-workbench.js:5374)
    at SVGGElement.o (d3.min.js:1)
    at d3.min.js:3
    at Y (d3.min.js:1)
    at Array.Co.each (d3.min.js:3)
    at Array.Co.attr (d3.min.js:3)
    at _graph.load (spectral-workbench.js:5373)
    at Object.success (spectral-workbench.js:127)
    at c (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
```

2020-09-29 16:58 UTC, jywarren commented
OK - this is a known error: https://github.com/publiclab/spectral-workbench.js/pull/165

Don't know why it's just suddenly showing up on Travis. Let's downgrade again and see.

2020-09-30 00:59 UTC, jywarren commented
Trying to bump d3 to `v3.5.4` because of https://github.com/publiclab/spectral-workbench.js/issues/180#issuecomment-701097109

graph demo works:

![image](https://user-images.githubusercontent.com/24359/94631373-491e3b00-0296-11eb-9502-2771c720e0dc.png)

new capture demo works:

![image](https://user-images.githubusercontent.com/24359/94631412-6eab4480-0296-11eb-9ef6-606ab8fab89f.png)

I think we could do this... but will `nvd3` work?

2020-09-30 01:03 UTC, jywarren commented
Aha ok, so: noting `"GET /node_modules/jquery.steps/build/jquery.steps.min.js" Error (404): "Not found"`

and, back to the original error:

```

     TypeError: undefined is not an object (evaluating 'd3.select('svg').data()[0][index].id') in file:///home/travis/build/publiclab/spectral-workbench.js/dist/spectral-workbench.js (line 5374) (1)
   - can copy calibrations with copyCalibration()...X can copy calibrations with copyCalibration()
     TypeError: undefined is not an object (evaluating 'graph.datum') in file:///home/travis/build/publiclab/spectral-workbench.js/spec/javascripts/api_spec.js (line 128) (1)
```

2020-10-06 16:12 UTC, jywarren commented
OK so we have trouble with d3 v3.5 - the known error in our codebase: #165

But v3.4 had caused us trouble with `contextify` -- specifically we bumped to v3.5.4 to resolve contextify issues in
02c1adc

So we are left with: 

1. solve the known error with `TypeError: undefined is not an object (evaluating 'd3.select('svg').data()[0][index].id') in file:///home/travis/build/publiclab/spectral-workbench.js/dist/spectral-workbench.js (line 5374) (1)`
2. find a pre-`v3.5.4` (or post!) version that does not have that error?

2020-11-14 21:44 UTC, jywarren commented
So, noting that this error would occur a LOT in this file:

https://github.com/publiclab/spectral-workbench.js/blob/7b52a773650951ab3a2b54c6ad60f8f117a6d72d/src/SpectralWorkbench.Graph.js#L234

because this segment causing it is repeatedly called in that file:

```js
var id = d3.select('svg').data()[0][index].id; // this is the real d3 DOM-stored data
```

2020-11-14 21:54 UTC, jywarren commented
Noting the error occurs in client side of the graph demo!

![image](https://user-images.githubusercontent.com/24359/99157778-083d8280-269a-11eb-89db-cc7b4e98eb38.png)

2020-11-14 22:26 UTC, jywarren commented
Hmm, maybe the two errors are different, `Cannot read property 'id' of undefined` vs `TypeError: undefined is not an object (evaluating 'd3.select('svg').data()[0][index].id')` -- but they seem to affect almost the same segment of code.

2020-11-14 23:54 UTC, jywarren commented
Solved `TypeError: undefined is not an object (evaluating 'd3.select('svg').data()[0][index].id') in file:///home/travis/build/publiclab/spectral-workbench.js/dist/spectral-workbench.js (line 5374) (1)` !!

Now we have one more error -- all these are returning incorrectly... could be related:

```
   X should initialize line styling and table rows properly
     Expected 1 to be 2. (1)
     Expected 1 to be 2. (2)
     Expected 1 to be 2. (3)
     Expected 1 to be 2. (4)
```

https://github.com/publiclab/spectral-workbench.js/blob/7b52a773650951ab3a2b54c6ad60f8f117a6d72d/spec/javascripts/set_spec.js#L54-L63

2020-11-15 03:00 UTC, jywarren commented
No more test failures!

Just:

```
101 specs in 14.061s.
>> 0 failures
Fatal error: Callback must be a function
The command "grunt jasmine" exited with 3.
```

2020-11-15 03:02 UTC, jywarren commented
Related to node 10, switched to 12! https://github.com/gruntjs/grunt-contrib-jasmine/issues/266

2020-11-15 03:31 UTC, jywarren commented
YES!!!! All done! Merging! Thank you!!!!

2020-11-15 03:32 UTC, merged